databases:
  - name: helloworld
    plan: free
    databaseName: helloworld
    user: helloworld

services:
  - type: web
    name: helloworld
    plan: free
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "./bin/render-start.sh"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: helloworld
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
