databases:
  - name: hello-world-2
    plan: free
    databaseName: hello-world-2
    user: hello-world-2

services:
  - type: web
    name: hello-world-2
    plan: free
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "./bin/render-start.sh"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: hello-world-2
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
