databases:
  - name: HelloWorld2
    plan: free
    databaseName: HelloWorld2
    user: HelloWorld2

services:
  - type: web
    name: HelloWorld2
    plan: free
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "./bin/render-start.sh"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: HelloWorld2
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
